export const GET_LATEST_OPTION_INFO = 'GET_LATEST_OPTION_INFO'
export const GET_HISTORICAL_OPTION_INFO = 'GET_HISTORICAL_OPTION_INFO'
export const LATEST_OPTION_INFO = 'LATEST_OPTION_INFO'
export const HISTORICAL_OPTION_INFO = 'HISTORICAL_OPTION_INFO'